C:\Users\me\.jdks\temurin-17.0.10\bin\java.exe -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\lib\idea_rt.jar=55711:C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4\plugins\testng\lib\testng-rt.jar;C:\workspaces\test\EasyMockErrorShowCase\target\test-classes;C:\workspaces\test\EasyMockErrorShowCase\target\classes;C:\Users\me\.m2\repository\org\testng\testng\7.10.1\testng-7.10.1.jar;C:\Users\me\.m2\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;C:\Users\me\.m2\repository\com\beust\jcommander\1.82\jcommander-1.82.jar;C:\Users\me\.m2\repository\org\webjars\jquery\3.7.1\jquery-3.7.1.jar;C:\Users\me\.m2\repository\org\easymock\easymock\5.2.0\easymock-5.2.0.jar;C:\Users\me\.m2\repository\org\objenesis\objenesis\3.3\objenesis-3.3.jar" com.intellij.rt.testng.RemoteTestNGStarter -usedefaultlisteners false -socket55710 @w@C:\Users\me\AppData\Local\Temp\idea_working_dirs_testng.tmp -temp C:\Users\me\AppData\Local\Temp\idea_testng.tmp
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.testng.TestNGException:
Cannot instantiate class ShowCaseTest
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:43)
	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:18)
	at org.testng.internal.objects.SimpleObjectDispenser.instantiateUsingDefaultConstructor(SimpleObjectDispenser.java:179)
	at org.testng.internal.objects.SimpleObjectDispenser.createInstance(SimpleObjectDispenser.java:88)
	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:41)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispenseObject(GuiceBasedObjectDispenser.java:41)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:31)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:107)
	at org.testng.internal.ClassImpl.getObjects(ClassImpl.java:140)
	at org.testng.internal.IObject.lambda$objects$0(IObject.java:59)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.testng.internal.IObject.objects(IObject.java:59)
	at org.testng.TestClass.getObjects(TestClass.java:150)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:126)
	at org.testng.TestClass.init(TestClass.java:118)
	at org.testng.TestClass.<init>(TestClass.java:83)
	at org.testng.TestRunner.initMethods(TestRunner.java:473)
	at org.testng.TestRunner.init(TestRunner.java:347)
	at org.testng.TestRunner.init(TestRunner.java:302)
	at org.testng.TestRunner.<init>(TestRunner.java:176)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:636)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:197)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1365)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1339)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1199)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:40)
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: no such field: com.sun.net.httpserver.HttpExchange$$$EasyMock$1.$callback/org.easymock.internal.ClassMockingData/putField
	at org.easymock.internal.ClassProxyFactory.getCallbackSetter(ClassProxyFactory.java:282)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:213)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:110)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:83)
	at org.easymock.EasyMockSupport.mock(EasyMockSupport.java:74)
	at org.easymock.EasyMockSupport.createMock(EasyMockSupport.java:361)
	at ShowCaseTest.<init>(ShowCaseTest.java:9)
	... 34 more
Caused by: java.lang.IllegalAccessException: no such field: com.sun.net.httpserver.HttpExchange$$$EasyMock$1.$callback/org.easymock.internal.ClassMockingData/putField
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:972)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3641)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:3043)
	at org.easymock.internal.ClassProxyFactory.getCallbackSetter(ClassProxyFactory.java:280)
	... 40 more
Caused by: java.lang.LinkageError: bad field type alias: class org.easymock.internal.ClassMockingData not visible from class com.sun.net.httpserver.HttpExchange$$$EasyMock$1
	at java.base/java.lang.invoke.MemberName.checkForTypeAlias(MemberName.java:886)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1089)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
	... 43 more

Process finished with exit code -1